### ISSUE TITLE
explain this functionalities here

### ISSUE THREAD

**Issue by sarvaratchagan** [dhamo-dharan/Project#1]
![screenshot_1](https://cloud.githubusercontent.com/assets/7565739/20100232/9c9644b8-a5e2-11e6-82f2-cd772e1fa775.png)

**Comment by dhamo-dharan** [comment]
when call a stored procedure, insert the values in the corresponding table

**Comment by sarvaratchagan** [comment]
could you please share your stored procedure code here?
